export interface tblCategoryChild {
  id: number;
  categoryCode: string | null;
  categoryName: string | null;
  idParent: number;
  description: string | null;
  creationDate: string | null;
  createdBy: string | null;
  lastUpdateDate: string | null;
  lastUpdatedBy: string | null;
  lastUpdateLogin: string | null;
  orgId: string | null;
  categoryType: string | null;
  content: string | null;
  tags: string | null;
  imageIcon: string | null;
  imageOwner: string | null;
  priceRange: string | null;
  visibleType: string | null;
  fixedContent: string | null;
  orderedNumber: string | null;
  urlRedirect: string | null;
  templateFile: string | null;
  visibleItemQty: string | null;
  urlCanonicalForSeo: string | null;
  linkForSeo: string | null;
  idexForSeo: string | null;
  enableChangeLink: string | null;
  metaTitle: string | null;
  metaKeyword: string | null;
  metaDescription: string | null;
  itemCount: number;
  status: string | null;
  priorityStatus: string | null;
  brandId: string | null;
  categoryAttribute: string | null;
  isBuildPc: string | null;
  isMegaMenu: string | null;
  isTradeIn: string | null;
}

export interface CardProductTradeIn {
  data: TradeInItem;
  tblTradeInHeaderModels: tblTradeInHeaderModels[]
}

export interface TradeInItem {
  accessory: string | null;
  attribute1: string | null;
  attribute2: string | null;
  attribute3: string | null;
  attribute4: string | null;
  attribute5: string | null;
  attribute6: string | null;
  attribute7: string | null;
  attribute8: string | null;
  attribute9: string | null;
  attribute10: string | null;
  attribute11: string | null;
  attribute12: string | null;
  attribute13: string | null;
  attribute14: string | null;
  attribute15: string | null;
  barcode: string | null;
  barcodeUsed: string | null;
  bestSaleStatus: string | null;
  brandId: string | null;
  categoryId: string | null;
  color: string | null;
  createdBy: string | null;
  creationDate: string | null;
  description: string | null;
  dimensionUomCode: string | null;
  discountValue: number | null;
  erpInventoryItemId: string | null;
  fullModelCode: string | null;
  hotStatus: string | null;
  id: number;
  inUse: string | null;
  isPromotional: string | null;
  itemCode: string | null;
  itemCost: number | null;
  itemName: string | null;
  itemSpec: string | null;
  itemSummary: string | null;
  lastUpdateDate: string | null;
  lastUpdateLogin: string | null;
  lastUpdatedBy: string | null;
  liked: number | null;
  longName: string | null;
  marketPrice: number | null;
  metaDescription: string | null;
  metaKeyword: string | null;
  metaTitle: string | null;
  newStatus: string | null;
  onhandQuantyty: string | null;
  onlineStatus: string | null;
  orderNumber: number | null;
  orgId: string | null;
  parentId: string | null;
  primaryImage: string | null;
  primaryUnitOfMeasure: string | null;
  primaryUomCode: string | null;
  profit: string | null;
  promotions: string | null;
  purchases: number | null;
  purpose: string | null;
  rate: string | null;
  rateCount: string | null;
  saleOffStatus: string | null;
  secondaryUomCode: string | null;
  sex: string | null;
  shortName: string | null;
  sku: string | null;
  style: string | null;
  tag: string | null;
  unitHeight: string | null;
  unitLength: string | null;
  unitPriceReference: number | null;
  unitSellingPrice: number | null;
  unitVolume: string | null;
  unitWeight: string | null;
  unitWidth: string | null;
  url: string | null;
  urlCanonical: string | null;
  vat: string | null;
  view: number | null;
  volumeUomCode: string | null;
  warrantyByCus: string | null;
  warrantyByPartner: string | null;
  warrantyDescrition: string | null;
  weightUomCode: string | null;
}

export interface tblTradeInHeaderModels {
  amountSupport: null;
  catId: number;
  createdBy: string | null;
  creationDate: string | null;
  id: number;
  lastUpdateBy: string | null;
  lastUpdateDate: string | null;
  measure: string | null;
  method: number | null;
  option: null;
  percentSupport: number;
  productCondition: string | null;
  status: string | null;
  tblTradeInLineModels: string | null;
}
