export interface detailVoucher {
    id:number;
    voucherCode:number|null;
    idVoucher:number|null;
    customerName:string|null;
    securityCode:number|null;
    description:string|null;
    serialCode:string|null;
    qrCodeContent:number|null;
    custId:number|null;
    email:string|null;
    mobileNumber:string|null;
    saleChannel:string|null;
    generateQrCodeDate:string|null;
    activeStatus:string|null;
    usageStatus:string|null;
    notifyDate:string|null;
    notifyChannel:string|null;
    notifyNumber:number|null;
    issueDate:string|null;
    expireDate:string|null;
    createBy:string|null;
    lastUpdateBy:string|null;
    lastUpdateDate:string|null;
    activeDate:string|null;
    orderNumber:string|null;
    orderDate:string|null;
    sendStatus:string|null;
    tblVoucherModels:tblVoucher[]
}

export interface tblVoucher {
    id:number;
    code:number|null;
    securityCode:number|null;
    description:string|null;
    value:number|null;
    totalNumber:number|null;
    applyToCust:string|null;
    applyToProduct:string|null;
    createDate:string|null;
    expireDate:string|null;
    createBy:string|null;
    lastUpdateBy:string|null;
    lastUpdateDate:string|null;
    sendTimer:string|null;
    sendStatus:string|null;
    cout:string|null;
    currency:string|null;
    tblVoucherDetailModels:[]
}